export const dataList = [
  {
    category: "shoes",
    img_url: "adidas1.jpeg",
    rate: "30.05",
    saleRate: "10",
    productName: "Adidas1",
    top_Products: true,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "adidas2.jpeg",
    rate: "22.45",
    saleRate: "12",
    productName: "Adidas2",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "adidas3.jpeg",
    rate: "18.05",
    productName: "Adidas3",
    top_Products: false,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "billion1.jpeg",
    rate: "35.05",
    saleRate: "22",
    productName: "Billion",
    top_Products: false,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "metronaut1.jpeg",
    rate: "30.05",
    saleRate: "5",
    productName: "Metronaut",
    top_Products: false,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "morten1.jpeg",
    rate: "40.05",
    saleRate: "12",
    productName: "Morten",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "nike1.jpeg",
    rate: "23.05",
    productName: "Nike1",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "nike2.jpeg",
    rate: "24.05",
    saleRate: "10",
    productName: "Nike2",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "nike3.jpeg",
    rate: "45.05",
    saleRate: "10",
    productName: "Nike3",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "nike4.jpeg",
    rate: "50.05",
    saleRate: "10",
    productName: "Nike4",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "nike5.jpeg",
    rate: "60.05",
    saleRate: "10",
    productName: "Nike5",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "puma1.jpeg",
    rate: "47.05",
    saleRate: "15",
    productName: "Puma1",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "puma2.jpeg",
    rate: "30.05",
    productName: "Puma2",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "puma3.jpeg",
    rate: "30.05",
    productName: "Puma3",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "puma4.jpeg",
    rate: "30.05",
    productName: "Puma4",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "puma5.jpeg",
    rate: "30.05",
    productName: "Puma5",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "reebok1.jpeg",
    rate: "30.05",
    productName: "Reebok1",
    top_Products: false,
    blob: false,
  },
  {
    category: "shoes",
    img_url: "reebok2.jpeg",
    rate: "30.05",
    productName: "Reebok2",
    top_Products: false,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "tripr1.jpeg",
    rate: "35.05",
    saleRate: "17",
    productName: "Tripr",
    top_Products: true,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "veirdo1.jpeg",
    rate: "32.05",
    saleRate: "10",
    productName: "Veirdo",
    top_Products: false,
    blob: false,
  },
  {
    category: "t-shirts",
    img_url: "weardo1.jpeg",
    rate: "30",
    saleRate: "10",
    productName: "Weardo",
    top_Products: true,
    blob: false,
  },
];
